CREATE TABLE Category (
    CategoryID SERIAL PRIMARY KEY,
    CategoryName VARCHAR(100) NOT NULL
);

CREATE TABLE Customer (
    CustomerID SERIAL PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE Product (
    ProductID SERIAL PRIMARY KEY,
    CategoryID INTEGER REFERENCES Category(CategoryID),
    Name VARCHAR(150) NOT NULL,
    Price NUMERIC(10, 2) NOT NULL
);
